# import-pure: no filesystem mutation
"""Import-pipeline intermediate representation.

`pancratius.ir` is the public node namespace. The implementation lives in
`nodes.py`; the neighboring `normalize` and `lower` modules are the two passes
that transform and lower this IR.
"""

from pancratius.ir.nodes import (
    Block,
    BlockQuote,
    Code,
    CodeBlock,
    ContainerInline,
    ContainerInlineNode,
    Diagnostic,
    DialogueLabel,
    DirectionalSpan,
    Document,
    Emphasis,
    EmphKind,
    Epigraph,
    FootnoteDef,
    FootnoteRef,
    Heading,
    ImageBlock,
    ImageInline,
    Inline,
    LineBreak,
    Link,
    ListBlock,
    Paragraph,
    Quoted,
    Signature,
    SoftBreak,
    Table,
    Text,
    ThematicBreak,
    UnknownBlock,
    UnknownInline,
    VerseBlock,
    VerseRole,
    is_container_inline,
    map_block_inlines,
    rebuild_container,
)

__all__ = (
    "Block",
    "BlockQuote",
    "Code",
    "CodeBlock",
    "ContainerInline",
    "ContainerInlineNode",
    "Diagnostic",
    "DialogueLabel",
    "DirectionalSpan",
    "Document",
    "Emphasis",
    "EmphKind",
    "Epigraph",
    "FootnoteDef",
    "FootnoteRef",
    "Heading",
    "ImageBlock",
    "ImageInline",
    "Inline",
    "LineBreak",
    "Link",
    "ListBlock",
    "Paragraph",
    "Quoted",
    "Signature",
    "SoftBreak",
    "Table",
    "Text",
    "ThematicBreak",
    "UnknownBlock",
    "UnknownInline",
    "VerseBlock",
    "VerseRole",
    "is_container_inline",
    "map_block_inlines",
    "rebuild_container",
)
